/**
 * @nami/shared - 常量导出入口
 */

export {
  RENDER_MODE_LABELS,
  SERVER_RENDER_MODES,
  STATIC_RENDER_MODES,
  NEEDS_SERVER_BUNDLE,
  needsServerRuntime,
  needsStaticGeneration,
} from './render-modes';

export { ERROR_MESSAGES, formatErrorMessage } from './error-codes';

export {
  DEFAULT_APP_NAME,
  DEFAULT_SRC_DIR,
  DEFAULT_OUT_DIR,
  DEFAULT_RENDER_MODE,
  DEFAULT_CONTAINER_ID,
  NAMI_DATA_VARIABLE,
  NAMI_DATA_API_PREFIX,
  NAMI_ISR_REVALIDATE_HEADER,
  ASSET_MANIFEST_FILENAME,
  NAMI_MANIFEST_FILENAME,
  DEFAULT_SERVER_CONFIG,
  DEFAULT_ISR_CONFIG,
  DEFAULT_MONITOR_CONFIG,
  DEFAULT_FALLBACK_CONFIG,
  DEFAULT_ASSETS_CONFIG,
  HEALTH_CHECK_PATH,
  ISR_REVALIDATE_PATH,
  MAX_SSR_TIMEOUT,
  MIN_REVALIDATE_INTERVAL,
  MAX_REVALIDATE_INTERVAL,
} from './defaults';
